apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-ui-config
  namespace: observability
data:
  jaeger-ui.json: |
    {
      "tracing": {
        "enabled": true,
        "defaultService": "jaeger-query"
      },
      "archiveEnabled": true,
      "dependencies": {
        "menuEnabled": true
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: observability
data:
  otel-collector-config.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
        logLevel: debug
      prometheus:
        endpoint: "0.0.0.0:8889"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector:8889']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: observability
data:
  grafana.ini: |
    [server]
    http_port = 3000
    [auth.anonymous]
    enabled = true
    org_role = Admin
    [auth]
    disable_login_form = true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: observability
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
