apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          args: ["--query.ui-config", "/etc/jaeger/jaeger-ui.json"]
          env:
            - name: METRICS_STORAGE_TYPE
              value: "prometheus"
            - name: PROMETHEUS_SERVER_URL
              value: "http://prometheus:9090"
            - name: PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR
              value: "true"
            - name: PROMETHEUS_QUERY_NAMESPACE
              value: ""
            - name: PROMETHEUS_QUERY_DURATION_UNIT
              value: ""
            - name: PROMETHEUS_QUERY_NORMALIZE_CALLS
              value: "true"
            - name: PROMETHEUS_QUERY_NORMALIZE_DURATION
              value: "true"
          volumeMounts:
            - name: jaeger-ui-config
              mountPath: /etc/jaeger/jaeger-ui.json
              subPath: jaeger-ui.json
          ports:
            - containerPort: 16685
            - containerPort: 16686
            - containerPort: 5778
            - containerPort: 14268
            - containerPort: 14269
            - containerPort: 14250
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 5775
            - containerPort: 6831
            - containerPort: 6832
      volumes:
        - name: jaeger-ui-config
          configMap:
            name: jaeger-ui-config

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: http-query
      protocol: TCP
      port: 16685
      targetPort: 16685
    - name: http-ui
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: agent-compact
      protocol: TCP
      port: 5778
      targetPort: 5778
    - name: collector-http
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: collector-grpc
      protocol: TCP
      port: 14269
      targetPort: 14269
    - name: collector-thrift
      protocol: TCP
      port: 14250
      targetPort: 14250
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: agent-compact-udp
      protocol: UDP
      port: 5775
      targetPort: 5775
    - name: agent-zipkin-udp
      protocol: UDP
      port: 6831
      targetPort: 6831
    - name: agent-jaeger-udp
      protocol: UDP
      port: 6832
      targetPort: 6832
